# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 937a1de882ebd1febe856a36f21c1290434b0d8f995a6614a45374f10164b04b485aa7dd2cd6878e240b3d4eafaeea4e11e7f12b7cbb86bcafebcfff41830d60

test:
  secret_key_base: 20e358a5a1ccb71b30ff4b5b17cba17dc93b4b4130e14ce150e32976a54e06333d4a5e22b322bab6569c247fcec161a23bce3f55a2d768c6648b0106542d50e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
