---
:concurrency: 5
<% require 'dotenv' %>
<% Dotenv.load %>
:pidfile: tmp/pids/sidekiq.pid
development:
  :concurrency: 1
  :queues:
    - [ <%= "#{ENV['QUEUE_PREFIX']}_report" %>, 12 ]
    - [ <%= "#{ENV['QUEUE_PREFIX']}_email" %>, 8 ]
    - [ <%= "#{ENV['QUEUE_PREFIX']}_push" %>, 12 ]
staging:
  :concurrency: 1
  :queues:
    - [ <%= "#{ENV['QUEUE_PREFIX']}_report" %>, 12 ]
    - [ <%= "#{ENV['QUEUE_PREFIX']}_email" %>, 8 ]
    - [ <%= "#{ENV['QUEUE_PREFIX']}_push" %>, 12 ]
production:
  :concurrency: 2
  :queues:
    - [ <%= "#{ENV['QUEUE_PREFIX']}_report" %>, 12 ]
    - [ <%= "#{ENV['QUEUE_PREFIX']}_email" %>, 8 ]
    - [ <%= "#{ENV['QUEUE_PREFIX']}_push" %>, 12 ]
:sidekiq_pid: File.join(shared_path, 'tmp', 'pids', 'sidekiq.pid')  