---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
  :queues:
    - [ staging_eretail_report, 12 ]
    - [ staging_eretail_email, 8 ]
    - [ staging_eretail_push, 12 ]
production:
  :concurrency: 25
  :queues:
    - [ production_eretail_report, 12 ]
    - [ production_eretail_email, 8 ]
    - [ production_eretail_push, 12 ]
:sidekiq_pid: File.join(shared_path, 'tmp', 'pids', 'sidekiq.pid')  